In [1]:
from massive import RESTClient
import pandas as pd

In [3]:
with open("key.txt") as file:
    API_key = file.read()

API_key = API_key.strip()

In [4]:
client = RESTClient(api_key=API_key)

In [5]:
def query_ohlcv(ticker,multiplier=1, timespan="day", start="2024-05-08", end="2026-05-07",adjusted=True):
    # List Aggregates (Bars)
    aggs = []
    for a in client.list_aggs(ticker=ticker, multiplier=1, timespan=timespan, from_=start, to=end,adjusted=adjusted):
        aggs.append(a)
    df = pd.DataFrame(aggs)
    df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
    df.to_csv(f"./ohlcv/{ticker}.csv")
    return df

In [6]:
ticker = "AAPL"
df = query_ohlcv(ticker=ticker, multiplier=1, timespan="day", start="2024-05-08", end="2026-05-07",adjusted=True)
df.head()

,open,high,low,close,volume,vwap,timestamp,transactions,otc,date
0,182.850,183.07,181.45,182.74,45057087.0,182.4822,1715140800000,518609,None,2024-05-08 04:00:00
1,182.560,184.66,182.11,184.57,48982972.0,184.0047,1715227200000,551005,None,2024-05-09 04:00:00
2,184.900,185.09,182.13,183.05,50759496.0,183.0973,1715313600000,558780,None,2024-05-10 04:00:00
3,185.435,187.10,184.62,186.28,72044809.0,186.2040,1715572800000,726520,None,2024-05-13 04:00:00
4,187.510,188.30,186.29,187.43,52393619.0,187.1924,1715659200000,559493,None,2024-05-14 04:00:00

In [7]:
df.tail()

,open,high,low,close,volume,vwap,timestamp,transactions,otc,date
496,278.855,287.22,278.3700,280.14,7.991544e+07,282.3707,1777608000000,1301741,None,2026-05-01 04:00:00
497,279.655,280.63,274.8601,276.83,4.666840e+07,276.9130,1777867200000,768696,None,2026-05-04 04:00:00
498,276.925,284.57,276.5010,284.18,4.931171e+07,282.4091,1777953600000,779580,None,2026-05-05 04:00:00
499,281.915,288.02,281.0700,287.51,5.832166e+07,286.3088,1778040000000,839415,None,2026-05-06 04:00:00
500,289.270,292.13,285.7800,287.44,4.522430e+07,288.7495,1778126400000,776365,None,2026-05-07 04:00:00

In [8]:
df.columns

Index(['open', 'high', 'low', 'close', 'volume', 'vwap', 'timestamp',
       'transactions', 'otc', 'date'],
      dtype='str')

In [42]:
import yfinance as yf
df = yf.download("AAPL", period="max", interval="1d")

[*********************100%***********************]  1 of 1 completed

In [43]:
df.head()

Price          Close      High       Low      Open     Volume
Ticker          AAPL      AAPL      AAPL      AAPL       AAPL
Date
1980-12-12  0.098298  0.098725  0.098298  0.098298  469033600
1980-12-15  0.093169  0.093597  0.093169  0.093597  175884800
1980-12-16  0.086331  0.086758  0.086331  0.086758  105728000
1980-12-17  0.088468  0.088895  0.088468  0.088468   86441600
1980-12-18  0.091032  0.091460  0.091032  0.091032   73449600

In [31]:
df.tail()

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-05-04  276.829987  280.630005  274.859985  279.660004  46668400
2026-05-05  284.179993  284.570007  276.500000  276.929993  49311700
2026-05-06  287.510010  288.029999  281.070007  281.920013  58336100
2026-05-07  287.440002  292.130005  285.779999  289.269989  45145500
2026-05-08  293.644989  294.554993  290.000000  290.109985   7029213

In [50]:
new_df = df.copy()

In [51]:
new_df.columns = new_df.columns.droplevel(1)

In [52]:
# Reset index to move 'Date' from the index to a column
new_df = new_df.rename_axis(None, axis=1)
new_df = new_df.reset_index()
new_df.head()

        Date     Close      High       Low      Open     Volume
0 1980-12-12  0.098298  0.098725  0.098298  0.098298  469033600
1 1980-12-15  0.093169  0.093597  0.093169  0.093597  175884800
2 1980-12-16  0.086331  0.086758  0.086331  0.086758  105728000
3 1980-12-17  0.088468  0.088895  0.088468  0.088468   86441600
4 1980-12-18  0.091032  0.091460  0.091032  0.091032   73449600

In [53]:
new_df.tail()

            Date       Close        High         Low        Open    Volume
11438 2026-05-04  276.829987  280.630005  274.859985  279.660004  46668400
11439 2026-05-05  284.179993  284.570007  276.500000  276.929993  49311700
11440 2026-05-06  287.510010  288.029999  281.070007  281.920013  58336100
11441 2026-05-07  287.440002  292.130005  285.779999  289.269989  45145500
11442 2026-05-08  292.029999  294.760010  290.000000  290.109985  23089232

In [55]:
new_df['year'] = new_df['Date'].dt.year

In [58]:
new_new_df = new_df.query("year >= 2000")

In [60]:
new_new_df['stock_id'] = 1

In [66]:
new_new_df = new_new_df.rename(columns ={
                    "Date":"date",
                    "Open":"open",
                    "Close":"close",
                    "Low":"low",
                    "High":"high",
                    "Volume":"volume"
                    })

In [70]:
new_new_df.to_csv("ohlcv.csv",index=False)

In [69]:
new_new_df.head()

,date,close,high,low,open,volume,year,stock_id
4816,2000-01-03,0.838496,0.842709,0.761716,0.785592,535796800,2000,1
4817,2000-01-04,0.767803,0.828664,0.757971,0.810874,512377600,2000,1
4818,2000-01-05,0.779038,0.828196,0.771547,0.777165,778321600,2000,1
4819,2000-01-06,0.711621,0.801510,0.711621,0.794956,767972800,2000,1
4820,2000-01-07,0.745330,0.756566,0.715367,0.722857,460734400,2000,1